// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql/driver"
	"fmt"
)

type AlbumReleaseDatePrecision string

const (
	AlbumReleaseDatePrecisionYear  AlbumReleaseDatePrecision = "year"
	AlbumReleaseDatePrecisionMonth AlbumReleaseDatePrecision = "month"
	AlbumReleaseDatePrecisionDay   AlbumReleaseDatePrecision = "day"
)

func (e *AlbumReleaseDatePrecision) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlbumReleaseDatePrecision(s)
	case string:
		*e = AlbumReleaseDatePrecision(s)
	default:
		return fmt.Errorf("unsupported scan type for AlbumReleaseDatePrecision: %T", src)
	}
	return nil
}

type NullAlbumReleaseDatePrecision struct {
	AlbumReleaseDatePrecision AlbumReleaseDatePrecision `json:"album_release_date_precision"`
	Valid                     bool                      `json:"valid"` // Valid is true if AlbumReleaseDatePrecision is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlbumReleaseDatePrecision) Scan(value interface{}) error {
	if value == nil {
		ns.AlbumReleaseDatePrecision, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlbumReleaseDatePrecision.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlbumReleaseDatePrecision) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlbumReleaseDatePrecision), nil
}

type AlbumType string

const (
	AlbumTypeAlbum       AlbumType = "album"
	AlbumTypeSingle      AlbumType = "single"
	AlbumTypeCompilation AlbumType = "compilation"
)

func (e *AlbumType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlbumType(s)
	case string:
		*e = AlbumType(s)
	default:
		return fmt.Errorf("unsupported scan type for AlbumType: %T", src)
	}
	return nil
}

type NullAlbumType struct {
	AlbumType AlbumType `json:"album_type"`
	Valid     bool      `json:"valid"` // Valid is true if AlbumType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlbumType) Scan(value interface{}) error {
	if value == nil {
		ns.AlbumType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlbumType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlbumType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlbumType), nil
}

type Album struct {
	ID                   string                    `json:"id"`
	AlbumType            AlbumType                 `json:"album_type"`
	TotalTracks          int64                     `json:"total_tracks"`
	ExternalUrls         map[string]string         `json:"external_urls"`
	Href                 string                    `json:"href"`
	Name                 string                    `json:"name"`
	ReleaseDate          string                    `json:"release_date"`
	ReleaseDatePrecision AlbumReleaseDatePrecision `json:"release_date_precision"`
	Uri                  string                    `json:"uri"`
	Genres               []string                  `json:"genres"`
}

type AlbumImage struct {
	AlbumID  string `json:"album_id"`
	ImageUrl string `json:"image_url"`
}

type Artist struct {
	ID           string            `json:"id"`
	ExternalUrls map[string]string `json:"external_urls"`
	Href         string            `json:"href"`
	Name         string            `json:"name"`
	Uri          string            `json:"uri"`
	Genres       []string          `json:"genres"`
}

type ArtistAlbum struct {
	ArtistID string `json:"artist_id"`
	AlbumID  string `json:"album_id"`
}

type ArtistImage struct {
	ArtistID string `json:"artist_id"`
	ImageUrl string `json:"image_url"`
}

type ArtistTrack struct {
	ArtistID string `json:"artist_id"`
	TrackID  string `json:"track_id"`
}

type Image struct {
	Url    string `json:"url"`
	Width  int64  `json:"width"`
	Height int64  `json:"height"`
}

type Playlist struct {
	ID           string            `json:"id"`
	ExternalUrls map[string]string `json:"external_urls"`
	Href         string            `json:"href"`
	Name         string            `json:"name"`
	Uri          string            `json:"uri"`
}

type PlaylistImage struct {
	PlaylistID string `json:"playlist_id"`
	ImageUrl   string `json:"image_url"`
}

type Track struct {
	ID           string            `json:"id"`
	DurationMs   int64             `json:"duration_ms"`
	Explicit     bool              `json:"explicit"`
	ExternalUrls map[string]string `json:"external_urls"`
	Href         string            `json:"href"`
	Name         string            `json:"name"`
	Popularity   int64             `json:"popularity"`
	PreviewUrl   *string           `json:"preview_url"`
	TrackNumber  int64             `json:"track_number"`
	Uri          string            `json:"uri"`
	AlbumID      string            `json:"album_id"`
}
