// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AlbumsColumns holds the columns for the "albums" table.
	AlbumsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "album_type", Type: field.TypeEnum, Enums: []string{"album", "single", "compilation"}},
		{Name: "total_tracks", Type: field.TypeInt},
		{Name: "available_markets", Type: field.TypeJSON},
		{Name: "external_urls", Type: field.TypeJSON},
		{Name: "href", Type: field.TypeString, Size: 2147483647},
		{Name: "name", Type: field.TypeString, Size: 2147483647},
		{Name: "release_date", Type: field.TypeString, Size: 2147483647},
		{Name: "release_date_precision", Type: field.TypeEnum, Enums: []string{"year", "month", "day"}},
		{Name: "restrictions", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "uri", Type: field.TypeString, Size: 2147483647},
		{Name: "genres", Type: field.TypeJSON},
		{Name: "label", Type: field.TypeString, Size: 2147483647},
		{Name: "popularity", Type: field.TypeInt},
	}
	// AlbumsTable holds the schema information for the "albums" table.
	AlbumsTable = &schema.Table{
		Name:       "albums",
		Columns:    AlbumsColumns,
		PrimaryKey: []*schema.Column{AlbumsColumns[0]},
	}
	// ArtistsColumns holds the columns for the "artists" table.
	ArtistsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "external_urls", Type: field.TypeJSON},
		{Name: "href", Type: field.TypeString, Size: 2147483647},
		{Name: "name", Type: field.TypeString, Size: 2147483647},
		{Name: "uri", Type: field.TypeString, Size: 2147483647},
	}
	// ArtistsTable holds the schema information for the "artists" table.
	ArtistsTable = &schema.Table{
		Name:       "artists",
		Columns:    ArtistsColumns,
		PrimaryKey: []*schema.Column{ArtistsColumns[0]},
	}
	// ImagesColumns holds the columns for the "images" table.
	ImagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "url", Type: field.TypeString},
		{Name: "width", Type: field.TypeInt},
		{Name: "height", Type: field.TypeInt},
		{Name: "text", Type: field.TypeString, Size: 2147483647},
	}
	// ImagesTable holds the schema information for the "images" table.
	ImagesTable = &schema.Table{
		Name:       "images",
		Columns:    ImagesColumns,
		PrimaryKey: []*schema.Column{ImagesColumns[0]},
	}
	// TracksColumns holds the columns for the "tracks" table.
	TracksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "available_markets", Type: field.TypeJSON},
		{Name: "disc_number", Type: field.TypeInt, Nullable: true},
		{Name: "duration_ms", Type: field.TypeInt},
		{Name: "explicit", Type: field.TypeBool, Default: false},
		{Name: "external_urls", Type: field.TypeJSON},
		{Name: "href", Type: field.TypeString, Size: 2147483647},
		{Name: "is_playable", Type: field.TypeBool},
		{Name: "name", Type: field.TypeString, Size: 2147483647},
		{Name: "popularity", Type: field.TypeInt},
		{Name: "preview_url", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "track_number", Type: field.TypeInt},
		{Name: "uri", Type: field.TypeString, Size: 2147483647},
		{Name: "album_id", Type: field.TypeString},
	}
	// TracksTable holds the schema information for the "tracks" table.
	TracksTable = &schema.Table{
		Name:       "tracks",
		Columns:    TracksColumns,
		PrimaryKey: []*schema.Column{TracksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tracks_albums_tracks",
				Columns:    []*schema.Column{TracksColumns[15]},
				RefColumns: []*schema.Column{AlbumsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// AlbumImagesColumns holds the columns for the "album_images" table.
	AlbumImagesColumns = []*schema.Column{
		{Name: "album_id", Type: field.TypeString},
		{Name: "image_id", Type: field.TypeString},
	}
	// AlbumImagesTable holds the schema information for the "album_images" table.
	AlbumImagesTable = &schema.Table{
		Name:       "album_images",
		Columns:    AlbumImagesColumns,
		PrimaryKey: []*schema.Column{AlbumImagesColumns[0], AlbumImagesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "album_images_album_id",
				Columns:    []*schema.Column{AlbumImagesColumns[0]},
				RefColumns: []*schema.Column{AlbumsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "album_images_image_id",
				Columns:    []*schema.Column{AlbumImagesColumns[1]},
				RefColumns: []*schema.Column{ImagesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// ArtistAlbumsColumns holds the columns for the "artist_albums" table.
	ArtistAlbumsColumns = []*schema.Column{
		{Name: "artist_id", Type: field.TypeString},
		{Name: "album_id", Type: field.TypeString},
	}
	// ArtistAlbumsTable holds the schema information for the "artist_albums" table.
	ArtistAlbumsTable = &schema.Table{
		Name:       "artist_albums",
		Columns:    ArtistAlbumsColumns,
		PrimaryKey: []*schema.Column{ArtistAlbumsColumns[0], ArtistAlbumsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "artist_albums_artist_id",
				Columns:    []*schema.Column{ArtistAlbumsColumns[0]},
				RefColumns: []*schema.Column{ArtistsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "artist_albums_album_id",
				Columns:    []*schema.Column{ArtistAlbumsColumns[1]},
				RefColumns: []*schema.Column{AlbumsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// ArtistTracksColumns holds the columns for the "artist_tracks" table.
	ArtistTracksColumns = []*schema.Column{
		{Name: "artist_id", Type: field.TypeString},
		{Name: "track_id", Type: field.TypeString},
	}
	// ArtistTracksTable holds the schema information for the "artist_tracks" table.
	ArtistTracksTable = &schema.Table{
		Name:       "artist_tracks",
		Columns:    ArtistTracksColumns,
		PrimaryKey: []*schema.Column{ArtistTracksColumns[0], ArtistTracksColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "artist_tracks_artist_id",
				Columns:    []*schema.Column{ArtistTracksColumns[0]},
				RefColumns: []*schema.Column{ArtistsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "artist_tracks_track_id",
				Columns:    []*schema.Column{ArtistTracksColumns[1]},
				RefColumns: []*schema.Column{TracksColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AlbumsTable,
		ArtistsTable,
		ImagesTable,
		TracksTable,
		AlbumImagesTable,
		ArtistAlbumsTable,
		ArtistTracksTable,
	}
)

func init() {
	TracksTable.ForeignKeys[0].RefTable = AlbumsTable
	AlbumImagesTable.ForeignKeys[0].RefTable = AlbumsTable
	AlbumImagesTable.ForeignKeys[1].RefTable = ImagesTable
	ArtistAlbumsTable.ForeignKeys[0].RefTable = ArtistsTable
	ArtistAlbumsTable.ForeignKeys[1].RefTable = AlbumsTable
	ArtistTracksTable.ForeignKeys[0].RefTable = ArtistsTable
	ArtistTracksTable.ForeignKeys[1].RefTable = TracksTable
}
