package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"fmt"

	"github.com/rustic-beans/spotify-viewer/ent"
	"github.com/rustic-beans/spotify-viewer/generated"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (ent.Noder, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []string) ([]ent.Noder, error) {
	panic(fmt.Errorf("not implemented: Nodes - nodes"))
}

// Albums is the resolver for the albums field.
func (r *queryResolver) Albums(ctx context.Context) ([]*ent.Album, error) {
	panic(fmt.Errorf("not implemented: Albums - albums"))
}

// Images is the resolver for the images field.
func (r *queryResolver) Images(ctx context.Context) ([]*ent.Image, error) {
	panic(fmt.Errorf("not implemented: Images - images"))
}

// Tracks is the resolver for the tracks field.
func (r *queryResolver) Tracks(ctx context.Context) ([]*ent.Track, error) {
	panic(fmt.Errorf("not implemented: Tracks - tracks"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *albumResolver) Tracks(ctx context.Context, obj *ent.Album) ([]*generated.Track, error) {
	panic(fmt.Errorf("not implemented: Tracks - tracks"))
}
func (r *Resolver) Album() generated.AlbumResolver { return &albumResolver{r} }
type albumResolver struct{ *Resolver }
*/
