// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"

	"entgo.io/contrib/entgql"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/albe2669/spotify-viewer/ent/settings"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Common entgql types.
type (
	Cursor         = entgql.Cursor[int]
	PageInfo       = entgql.PageInfo[int]
	OrderDirection = entgql.OrderDirection
)

func orderFunc(o OrderDirection, field string) func(*sql.Selector) {
	if o == entgql.OrderDirectionDesc {
		return Desc(field)
	}
	return Asc(field)
}

const errInvalidPagination = "INVALID_PAGINATION"

func validateFirstLast(first, last *int) (err *gqlerror.Error) {
	switch {
	case first != nil && last != nil:
		err = &gqlerror.Error{
			Message: "Passing both `first` and `last` to paginate a connection is not supported.",
		}
	case first != nil && *first < 0:
		err = &gqlerror.Error{
			Message: "`first` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	case last != nil && *last < 0:
		err = &gqlerror.Error{
			Message: "`last` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	}
	return err
}

func collectedField(ctx context.Context, path ...string) *graphql.CollectedField {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return nil
	}
	field := fc.Field
	oc := graphql.GetOperationContext(ctx)
walk:
	for _, name := range path {
		for _, f := range graphql.CollectFields(oc, field.Selections, nil) {
			if f.Alias == name {
				field = f
				continue walk
			}
		}
		return nil
	}
	return &field
}

func hasCollectedField(ctx context.Context, path ...string) bool {
	if graphql.GetFieldContext(ctx) == nil {
		return true
	}
	return collectedField(ctx, path...) != nil
}

const (
	edgesField      = "edges"
	nodeField       = "node"
	pageInfoField   = "pageInfo"
	totalCountField = "totalCount"
)

func paginateLimit(first, last *int) int {
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	return limit
}

// SettingsEdge is the edge representation of Settings.
type SettingsEdge struct {
	Node   *Settings `json:"node"`
	Cursor Cursor    `json:"cursor"`
}

// SettingsConnection is the connection containing edges to Settings.
type SettingsConnection struct {
	Edges      []*SettingsEdge `json:"edges"`
	PageInfo   PageInfo        `json:"pageInfo"`
	TotalCount int             `json:"totalCount"`
}

func (c *SettingsConnection) build(nodes []*Settings, pager *settingsPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Settings
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Settings {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Settings {
			return nodes[i]
		}
	}
	c.Edges = make([]*SettingsEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &SettingsEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// SettingsPaginateOption enables pagination customization.
type SettingsPaginateOption func(*settingsPager) error

// WithSettingsOrder configures pagination ordering.
func WithSettingsOrder(order *SettingsOrder) SettingsPaginateOption {
	if order == nil {
		order = DefaultSettingsOrder
	}
	o := *order
	return func(pager *settingsPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultSettingsOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithSettingsFilter configures pagination filter.
func WithSettingsFilter(filter func(*SettingsQuery) (*SettingsQuery, error)) SettingsPaginateOption {
	return func(pager *settingsPager) error {
		if filter == nil {
			return errors.New("SettingsQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type settingsPager struct {
	reverse bool
	order   *SettingsOrder
	filter  func(*SettingsQuery) (*SettingsQuery, error)
}

func newSettingsPager(opts []SettingsPaginateOption, reverse bool) (*settingsPager, error) {
	pager := &settingsPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultSettingsOrder
	}
	return pager, nil
}

func (p *settingsPager) applyFilter(query *SettingsQuery) (*SettingsQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *settingsPager) toCursor(s *Settings) Cursor {
	return p.order.Field.toCursor(s)
}

func (p *settingsPager) applyCursors(query *SettingsQuery, after, before *Cursor) (*SettingsQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultSettingsOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *settingsPager) applyOrder(query *SettingsQuery) *SettingsQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultSettingsOrder.Field {
		query = query.Order(DefaultSettingsOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *settingsPager) orderExpr(query *SettingsQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultSettingsOrder.Field {
			b.Comma().Ident(DefaultSettingsOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Settings.
func (s *SettingsQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...SettingsPaginateOption,
) (*SettingsConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newSettingsPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if s, err = pager.applyFilter(s); err != nil {
		return nil, err
	}
	conn := &SettingsConnection{Edges: []*SettingsEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			c := s.Clone()
			c.ctx.Fields = nil
			if conn.TotalCount, err = c.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if s, err = pager.applyCursors(s, after, before); err != nil {
		return nil, err
	}
	limit := paginateLimit(first, last)
	if limit != 0 {
		s.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := s.collectField(ctx, limit == 1, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	s = pager.applyOrder(s)
	nodes, err := s.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// SettingsOrderField defines the ordering field of Settings.
type SettingsOrderField struct {
	// Value extracts the ordering value from the given Settings.
	Value    func(*Settings) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) settings.OrderOption
	toCursor func(*Settings) Cursor
}

// SettingsOrder defines the ordering of Settings.
type SettingsOrder struct {
	Direction OrderDirection      `json:"direction"`
	Field     *SettingsOrderField `json:"field"`
}

// DefaultSettingsOrder is the default ordering of Settings.
var DefaultSettingsOrder = &SettingsOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &SettingsOrderField{
		Value: func(s *Settings) (ent.Value, error) {
			return s.ID, nil
		},
		column: settings.FieldID,
		toTerm: settings.ByID,
		toCursor: func(s *Settings) Cursor {
			return Cursor{ID: s.ID}
		},
	},
}

// ToEdge converts Settings into SettingsEdge.
func (s *Settings) ToEdge(order *SettingsOrder) *SettingsEdge {
	if order == nil {
		order = DefaultSettingsOrder
	}
	return &SettingsEdge{
		Node:   s,
		Cursor: order.Field.toCursor(s),
	}
}
