// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/albe2669/spotify-viewer/ent/schema"
	"github.com/albe2669/spotify-viewer/ent/settings"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	settingsFields := schema.Settings{}.Fields()
	_ = settingsFields
	// settingsDescKey is the schema descriptor for key field.
	settingsDescKey := settingsFields[0].Descriptor()
	// settings.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	settings.KeyValidator = settingsDescKey.Validators[0].(func(string) error)
	// settingsDescValue is the schema descriptor for value field.
	settingsDescValue := settingsFields[1].Descriptor()
	// settings.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	settings.ValueValidator = settingsDescValue.Validators[0].(func(string) error)
}
