// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/albe2669/spotify-viewer/ent/schema/pulid"
	"github.com/albe2669/spotify-viewer/ent/track"
)

// TrackCreate is the builder for creating a Track entity.
type TrackCreate struct {
	config
	mutation *TrackMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (tc *TrackCreate) SetCreatedAt(t time.Time) *TrackCreate {
	tc.mutation.SetCreatedAt(t)
	return tc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tc *TrackCreate) SetNillableCreatedAt(t *time.Time) *TrackCreate {
	if t != nil {
		tc.SetCreatedAt(*t)
	}
	return tc
}

// SetUpdatedAt sets the "updated_at" field.
func (tc *TrackCreate) SetUpdatedAt(t time.Time) *TrackCreate {
	tc.mutation.SetUpdatedAt(t)
	return tc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tc *TrackCreate) SetNillableUpdatedAt(t *time.Time) *TrackCreate {
	if t != nil {
		tc.SetUpdatedAt(*t)
	}
	return tc
}

// SetTrackID sets the "track_id" field.
func (tc *TrackCreate) SetTrackID(pu pulid.ID) *TrackCreate {
	tc.mutation.SetTrackID(pu)
	return tc
}

// SetName sets the "name" field.
func (tc *TrackCreate) SetName(s string) *TrackCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetArtists sets the "artists" field.
func (tc *TrackCreate) SetArtists(s []string) *TrackCreate {
	tc.mutation.SetArtists(s)
	return tc
}

// SetArtistsGenres sets the "artists_genres" field.
func (tc *TrackCreate) SetArtistsGenres(s []string) *TrackCreate {
	tc.mutation.SetArtistsGenres(s)
	return tc
}

// SetAlbumName sets the "album_name" field.
func (tc *TrackCreate) SetAlbumName(s string) *TrackCreate {
	tc.mutation.SetAlbumName(s)
	return tc
}

// SetAlbumImageURI sets the "album_image_uri" field.
func (tc *TrackCreate) SetAlbumImageURI(s string) *TrackCreate {
	tc.mutation.SetAlbumImageURI(s)
	return tc
}

// SetDurationMs sets the "duration_ms" field.
func (tc *TrackCreate) SetDurationMs(i int32) *TrackCreate {
	tc.mutation.SetDurationMs(i)
	return tc
}

// SetURI sets the "uri" field.
func (tc *TrackCreate) SetURI(s string) *TrackCreate {
	tc.mutation.SetURI(s)
	return tc
}

// SetID sets the "id" field.
func (tc *TrackCreate) SetID(pu pulid.ID) *TrackCreate {
	tc.mutation.SetID(pu)
	return tc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tc *TrackCreate) SetNillableID(pu *pulid.ID) *TrackCreate {
	if pu != nil {
		tc.SetID(*pu)
	}
	return tc
}

// Mutation returns the TrackMutation object of the builder.
func (tc *TrackCreate) Mutation() *TrackMutation {
	return tc.mutation
}

// Save creates the Track in the database.
func (tc *TrackCreate) Save(ctx context.Context) (*Track, error) {
	tc.defaults()
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TrackCreate) SaveX(ctx context.Context) *Track {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TrackCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TrackCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *TrackCreate) defaults() {
	if _, ok := tc.mutation.CreatedAt(); !ok {
		v := track.DefaultCreatedAt()
		tc.mutation.SetCreatedAt(v)
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		v := track.DefaultUpdatedAt()
		tc.mutation.SetUpdatedAt(v)
	}
	if _, ok := tc.mutation.ID(); !ok {
		v := track.DefaultID()
		tc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TrackCreate) check() error {
	if _, ok := tc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Track.created_at"`)}
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Track.updated_at"`)}
	}
	if _, ok := tc.mutation.TrackID(); !ok {
		return &ValidationError{Name: "track_id", err: errors.New(`ent: missing required field "Track.track_id"`)}
	}
	if v, ok := tc.mutation.TrackID(); ok {
		if err := track.TrackIDValidator(string(v)); err != nil {
			return &ValidationError{Name: "track_id", err: fmt.Errorf(`ent: validator failed for field "Track.track_id": %w`, err)}
		}
	}
	if _, ok := tc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Track.name"`)}
	}
	if _, ok := tc.mutation.Artists(); !ok {
		return &ValidationError{Name: "artists", err: errors.New(`ent: missing required field "Track.artists"`)}
	}
	if _, ok := tc.mutation.ArtistsGenres(); !ok {
		return &ValidationError{Name: "artists_genres", err: errors.New(`ent: missing required field "Track.artists_genres"`)}
	}
	if _, ok := tc.mutation.AlbumName(); !ok {
		return &ValidationError{Name: "album_name", err: errors.New(`ent: missing required field "Track.album_name"`)}
	}
	if _, ok := tc.mutation.AlbumImageURI(); !ok {
		return &ValidationError{Name: "album_image_uri", err: errors.New(`ent: missing required field "Track.album_image_uri"`)}
	}
	if _, ok := tc.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "Track.duration_ms"`)}
	}
	if _, ok := tc.mutation.URI(); !ok {
		return &ValidationError{Name: "uri", err: errors.New(`ent: missing required field "Track.uri"`)}
	}
	return nil
}

func (tc *TrackCreate) sqlSave(ctx context.Context) (*Track, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*pulid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TrackCreate) createSpec() (*Track, *sqlgraph.CreateSpec) {
	var (
		_node = &Track{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(track.Table, sqlgraph.NewFieldSpec(track.FieldID, field.TypeString))
	)
	if id, ok := tc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := tc.mutation.CreatedAt(); ok {
		_spec.SetField(track.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tc.mutation.UpdatedAt(); ok {
		_spec.SetField(track.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := tc.mutation.TrackID(); ok {
		_spec.SetField(track.FieldTrackID, field.TypeString, value)
		_node.TrackID = value
	}
	if value, ok := tc.mutation.Name(); ok {
		_spec.SetField(track.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := tc.mutation.Artists(); ok {
		_spec.SetField(track.FieldArtists, field.TypeJSON, value)
		_node.Artists = value
	}
	if value, ok := tc.mutation.ArtistsGenres(); ok {
		_spec.SetField(track.FieldArtistsGenres, field.TypeJSON, value)
		_node.ArtistsGenres = value
	}
	if value, ok := tc.mutation.AlbumName(); ok {
		_spec.SetField(track.FieldAlbumName, field.TypeString, value)
		_node.AlbumName = value
	}
	if value, ok := tc.mutation.AlbumImageURI(); ok {
		_spec.SetField(track.FieldAlbumImageURI, field.TypeString, value)
		_node.AlbumImageURI = value
	}
	if value, ok := tc.mutation.DurationMs(); ok {
		_spec.SetField(track.FieldDurationMs, field.TypeInt32, value)
		_node.DurationMs = value
	}
	if value, ok := tc.mutation.URI(); ok {
		_spec.SetField(track.FieldURI, field.TypeString, value)
		_node.URI = value
	}
	return _node, _spec
}

// TrackCreateBulk is the builder for creating many Track entities in bulk.
type TrackCreateBulk struct {
	config
	err      error
	builders []*TrackCreate
}

// Save creates the Track entities in the database.
func (tcb *TrackCreateBulk) Save(ctx context.Context) ([]*Track, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Track, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TrackMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TrackCreateBulk) SaveX(ctx context.Context) []*Track {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TrackCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TrackCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
